#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.ea31e4.name = "1.8.3~ynh10"
    test_upgrade_from.6c6531.name = "1.9.0~ynh3"
