#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Updating configuration files..."

ynh_replace --match="https://$old_domain$old_path" --replace="https://$domain$path" --file="/etc/cron.d/$app"

#=================================================
# UPDATE THE DATABASE
#=================================================
ynh_script_progression "Updating the database..."

ynh_psql_db_shell <<< "UPDATE leed_configuration SET value='$domain$path/' WHERE value LIKE '%${old_domain}%'"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
