#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="PHP message: Leed: wrong login for .* client: <HOST>"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Finalizing installation..."

ynh_local_curl "/install.php?installButton" \
    "install_changeLngLeed=$language" \
    "root=$domain$path" \
    "mysqlHost=localhost" \
    "mysqlLogin=$db_user" \
    "mysqlMdp=$db_pwd" \
    "mysqlBase=$db_name" \
    "mysqlPrefix=leed_" \
    "login=$admin" \
    "password=$password"

# Create cron file
code_sync=$(ynh_psql_db_shell <<< 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)
ynh_config_add --template="cron_leed" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
